jokes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/registration/', views.registration, name='registration'),
    path('add_joke/', views.add_joke, name='add_joke'),
    path('add_favorite/<str:quote>', views.add_favorite, name='add_favorite'),
    path('delete_joke/<int:pk>', views.delete_joke, name='delete_joke'),
    path('update/<int:pk>', views.update_joke, name='update_joke'),
    path('edit/<int:pk>', views.edit_joke, name='edit_joke'),
    path('view/<int:pk>', views.view_joke, name='view_joke'),
]

selectel_test/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from selectel_test import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jokes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jokes/models.py
from django.db import models
from django.contrib.auth.models import User


class Joke(models.Model):
    joke_text = models.CharField(max_length=255)
    add_time = models.DateTimeField(auto_now_add=True, blank=False)
    user_joke = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)


class JokeOwner(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    email = models.CharField(max_length=20, verbose_name='Email', null=True, blank=True)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    jokes = models.ManyToManyField('Joke', verbose_name='Шутки пользователя', related_name='related_jokes')

jokes/forms.py
from django import forms
from django.contrib.auth.models import User

from jokes.models import Joke


class RegistrationForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Login'
        self.fields['password'].label = 'Password'
        self.fields['confirm_password'].label = 'Password'
        self.fields['phone'].label = 'Phone'
        self.fields['address'].label = 'Address'
        self.fields['first_name'].label = 'First name'
        self.fields['last_name'].label = 'Last name'
        self.fields['email'].label = 'Email'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['com', 'net']:
            raise forms.ValidationError(f'Регистрация домена {domain} невозможна')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Данный электронный адрес уже зарегестрирован')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError(f'Пароли не совпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']


class JokeForm(forms.ModelForm):
    class Meta:
        model = Joke
        fields = ['joke_text']
        widgets = {'joke_text': forms.TextInput(attrs={'class': 'form-control'}),
                   }

jokes/views.py
from datetime import date

from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
import requests
from .forms import RegistrationForm, JokeForm
from .models import *

menu = [{'title': "Главная(все шутки)", 'url_name': 'home'},
        {'title': "Добавить шутку", 'url_name': 'add_joke'},
        {'title': "Личный кабинет(свои шутки)", 'url_name': 'profile'},
        {'title': "Войти", 'url_name': 'login'}
        ]


def index(request):
    url = 'https://geek-jokes.sameerkumar.website/api'
    joke = requests.get(url).text[1:-2]
    context = {'menu': menu, 'joke': joke}
    return render(request, 'jokes/index.html', context)


def registration(request):
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.username = form.cleaned_data['username']
        new_user.email = form.cleaned_data['email']
        new_user.first_name = form.cleaned_data['first_name']
        new_user.last_name = form.cleaned_data['last_name']
        new_user.save()
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        JokeOwner.objects.create(
            user=new_user,
            email=form.cleaned_data['email'],
            phone=form.cleaned_data['phone'],
            address=form.cleaned_data['address']
        )
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        login(request, user)
        return HttpResponseRedirect('/')
    return render(request, 'registration/login.html', {'form': form})


def add_joke(request):
    if request.method == "POST":
        form = JokeForm(request.POST)
        if form.is_valid():
            try:
                Joke.objects.create(joke_text=form.cleaned_data['joke_text'], add_time=date.today(),
                                    user_joke=request.user)
                return redirect('/')
            except:
                pass
        else:
            return form.errors
    else:
        form = JokeForm()
    return render(request, 'jokes/add_joke.html', {'form': form})


def profile(request):
    user = request.user
    jokes = Joke.objects.filter(user_joke__username=user)
    context = {'menu': menu, 'jokes': jokes}
    return render(request, 'jokes/profile.html', context)


def add_favorite(request, quote):
    try:
        if request.method == 'GET':
            new_favorite_joke = Joke.objects.create(
                joke_text=quote,
                add_time=date.today(),
                user_joke=request.user
            )
            new_favorite_joke.save()
            return HttpResponseRedirect('/')
        else:
            return JsonResponse({'data': False})
    except:
        return JsonResponse({'data': False})


def edit_joke(request, pk):
    joke = Joke.objects.get(pk=pk)
    return render(request, 'jokes/update.html', {'joke': joke})


def update_joke(request, pk):
    try:
        joke = Joke.objects.get(pk=pk)
        form = JokeForm(request.POST, instance=joke)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/accounts/profile/')
            else:
                return form.errors
    except:
        return JsonResponse({'data': False})
    return render(request, 'jokes/update.html', {'joke': joke})


def delete_joke(request, pk):
    try:
        joke = Joke.objects.get(pk=pk)
        if request.method == 'GET':
            joke.delete()
            return HttpResponseRedirect('/accounts/profile/')
    except:
        return JsonResponse({'data': False})
    return render(request, 'jokes/profile.html', {'joke': joke})


def view_joke(request, pk):
    try:
        joke = Joke.objects.get(pk=pk)
        user = request.user
        if joke.user_joke == user:
            return HttpResponse(f"<p>{joke.joke_text}</p>")
        else:
            return HttpResponse("<p>Нет доступа к этой шутке</p>")
    except:
        return HttpResponse("<p>Нет шутки с таким ID или Вы не вошли в систему</p>")

templates/jokes/add_joke.html
{% extends "jokes/base.html" %}
 
{% block title %}Add New Employee Records{% endblock title %}
 
{% block content %}
<div class="col-md-12">
    <h4>Добавление шутки</h4>
         
 <form method="POST" class="post-form" action="{% url 'add_joke' %}">
   {% csrf_token %}  
  <div class="container">  
 <br>
   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Текст шутки:</label>
  <div class="col-sm-4">  
    {{ form.joke_text }}
  </div>  
   </div>  


  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-primary">Submit</button>  
  </div>  
   </div>  
  </div>  
 </form>  
</div> 
{% endblock content %} 

templates/jokes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Заголовок</title>
    <link type="text/css" href="{% static 'jokes/css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'jokes/css/bootstrap.min.css' %}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

</head>


<body>
{% block mainmenu %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Главная</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">

            {% if request.user.is_authenticated %}
                <li>
                <a class="nav-link text-link" href="{% url 'add_joke' %}">Добавить шутку</a>
                </li>

                <li>
                <a class="nav-link text-link" href="{% url 'profile' %}">Личный кабинет</a>
                </li>

                <li>
                <a class="nav-link text-link" href="{% url 'logout' %}">Выход</a>
                </li>

                {% else %}
                <li>
                <a class="nav-link text-link" href="{% url 'login' %}">Авторизация</a>
                </li>

                <li>
                <a class="nav-link text-link" href="{% url 'registration' %}">Регистрация</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock mainmenu %}

<div class="content-text">
    {% block content %}
    {% endblock %}
</div>

    <script src="{% static 'jokes/js/script.js' %}"></script>
</body>
</html>

templates/jokes/index.html
{% extends 'jokes/base.html' %}

{% block content %}
    {% if not request.user.is_authenticated %}
    <h3>{{ joke }}</h3>
    {% else %}
    <h3>{{ joke }}</h3>
    <span><a href="{% url 'add_favorite' joke %}" class="btn btn-primary">Сохранить шутку</a></span>
    {% endif %}

{% endblock %}

templates/jokes/profile.html
{% extends 'jokes/base.html' %}

{% block content %}
    {% for joke in jokes %}
        <h1>{{ joke.joke_text }}</h1>
        <a href="{% url 'edit_joke' joke.pk %}"
           class="btn btn-primary btn-xs"
           data-title="Edit" data-toggle="modal"
           data-target="#edit"><span
                class="glyphicon glyphicon-pencil"></span></a>
        <a href="{% url 'delete_joke' joke.id %}"
           class="btn btn-danger btn-xs"
           data-title="Delete" data-toggle="modal"
           data-target="#delete"><span
                class="glyphicon glyphicon-trash"></span></a>
    {% endfor %}
    <br>
{% endblock %}

templates/jokes/update.html
{% extends "jokes/base.html" %}

{% block content %}
        <h2>Изменение шутки</h2>
        <form method="POST" class="post-form" action="{% url 'update_joke' joke.id %}">
            {% csrf_token %}
            <br>
                    <label class="col-sm-2 col-form-label">Текст шутки</label>
                    <div class="col-sm-4">
                        <input type="text" name="joke_text" id="id_joke_text"
                               value="{{ joke.joke_text }}"/>
                    </div>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-primary">Обновить</button>
                    </div>
        </form>

{% endblock content %}

templates/jokes/view_joke.html
{% extends 'jokes/base.html' %}

{% block content %}
    <h3>{{ joke }}</h3>
{% endblock %}